<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>zuno.output</string>
        <key>name</key>
        <string>zuno-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Начало\]|\[Информация\])(.*)</string>
                <key>name</key>
                <string>zuno-output.start</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Готово\])(.+)</string>
                <key>name</key>
                <string>zuno-output.done</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Ошибка\])(.+)</string>
                <key>name</key>
                <string>zuno-output.errro</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.warning-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Внимание\])(.+)</string>
                <key>name</key>
                <string>zuno-output.warning</string>
            </dict>
        </array>
    </dict>
</plist>